#!/bin/bash
# Bootstrap script for creating Azure Storage backend for Terraform state
# Run this ONCE before first deployment

set -e

echo "=========================================="
echo "Terraform Backend Bootstrap"
echo "=========================================="

# Configuration
BACKEND_RG_NAME="rg-terraform-state"
BACKEND_LOCATION="eastus"
STORAGE_ACCOUNT_PREFIX="tfstate"
CONTAINER_NAME="tfstate"

# Generate unique storage account name
UNIQUE_ID=$(LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c 8)
STORAGE_ACCOUNT_NAME="${STORAGE_ACCOUNT_PREFIX}${UNIQUE_ID}"

echo "Configuration:"
echo "  Resource Group: $BACKEND_RG_NAME"
echo "  Location: $BACKEND_LOCATION"
echo "  Storage Account: $STORAGE_ACCOUNT_NAME"
echo "  Container: $CONTAINER_NAME"
echo ""

# Check Azure CLI authentication
echo "Checking Azure CLI authentication..."
if ! az account show &> /dev/null; then
    echo "❌ Not logged in to Azure. Please run 'az login' first."
    exit 1
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
echo "✅ Authenticated to Azure"
echo "   Subscription: $SUBSCRIPTION_NAME ($SUBSCRIPTION_ID)"
echo ""

# Create resource group for Terraform state
echo "Creating resource group..."
if az group show --name $BACKEND_RG_NAME &> /dev/null; then
    echo "⚠️  Resource group $BACKEND_RG_NAME already exists"
else
    az group create \
        --name $BACKEND_RG_NAME \
        --location $BACKEND_LOCATION \
        --tags "Purpose=TerraformState" "ManagedBy=Script"
    echo "✅ Resource group created"
fi
echo ""

# Create storage account
echo "Creating storage account..."
if az storage account show --name $STORAGE_ACCOUNT_NAME --resource-group $BACKEND_RG_NAME &> /dev/null; then
    echo "⚠️  Storage account $STORAGE_ACCOUNT_NAME already exists"
else
    az storage account create \
        --name $STORAGE_ACCOUNT_NAME \
        --resource-group $BACKEND_RG_NAME \
        --location $BACKEND_LOCATION \
        --sku Standard_LRS \
        --kind StorageV2 \
        --encryption-services blob \
        --https-only true \
        --min-tls-version TLS1_2 \
        --allow-blob-public-access false
    echo "✅ Storage account created"
fi
echo ""

# Enable versioning for state file protection
echo "Enabling blob versioning..."
az storage account blob-service-properties update \
    --account-name $STORAGE_ACCOUNT_NAME \
    --resource-group $BACKEND_RG_NAME \
    --enable-versioning true
echo "✅ Blob versioning enabled"
echo ""

# Create blob container
echo "Creating blob container..."
STORAGE_ACCOUNT_KEY=$(az storage account keys list \
    --resource-group $BACKEND_RG_NAME \
    --account-name $STORAGE_ACCOUNT_NAME \
    --query '[0].value' -o tsv)

if az storage container show \
    --name $CONTAINER_NAME \
    --account-name $STORAGE_ACCOUNT_NAME \
    --account-key $STORAGE_ACCOUNT_KEY &> /dev/null; then
    echo "⚠️  Container $CONTAINER_NAME already exists"
else
    az storage container create \
        --name $CONTAINER_NAME \
        --account-name $STORAGE_ACCOUNT_NAME \
        --account-key $STORAGE_ACCOUNT_KEY
    echo "✅ Container created"
fi
echo ""

# Generate backend configuration
echo "=========================================="
echo "Backend Configuration Complete!"
echo "=========================================="
echo ""
echo "Add the following to terraform/backend.tf:"
echo ""
echo "terraform {"
echo "  backend \"azurerm\" {"
echo "    resource_group_name  = \"$BACKEND_RG_NAME\""
echo "    storage_account_name = \"$STORAGE_ACCOUNT_NAME\""
echo "    container_name       = \"$CONTAINER_NAME\""
echo "    key                  = \"aks-openwebui-poc.tfstate\""
echo "  }"
echo "}"
echo ""
echo "=========================================="
echo ""

# Update backend.tf file
BACKEND_FILE="../terraform/backend.tf"
if [ -f "$BACKEND_FILE" ]; then
    echo "Updating $BACKEND_FILE..."
    cat > $BACKEND_FILE << EOF
# Backend configuration for Terraform state storage in Azure Storage
# Generated by bootstrap-backend.sh

terraform {
  backend "azurerm" {
    resource_group_name  = "$BACKEND_RG_NAME"
    storage_account_name = "$STORAGE_ACCOUNT_NAME"
    container_name       = "$CONTAINER_NAME"
    key                  = "aks-openwebui-poc.tfstate"
  }
}
EOF
    echo "✅ backend.tf updated"
else
    echo "⚠️  backend.tf not found at $BACKEND_FILE"
    echo "   Please create it manually with the configuration above"
fi
echo ""

echo "✅ Bootstrap complete! You can now run terraform init in the terraform/ directory."
